#!/bin/sh
set -e

runpath="$( cd "$(dirname "$0")/ops/dev" ; pwd -P )"

if [ ! -f "${runpath}/app_env.secrets" ]; then
    (cd ${runpath} && touch app_env.secrets)
fi

(cd ${runpath} && docker compose $@)