version: "3.3"
services:
  spot_utils:
    hostname: django
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - '80:8000'
    volumes:
      - ./api:/usr/src/app/api
      - ./web:/usr/src/app/web
      - ./spotUtils:/usr/src/app/spot_utils
