#!/bin/sh

# EXIT IF ANY OF THE FOLLOWING COMMANDS FAIL
set -e

IMAGE_NAME="ghcr.io/cstc-wtcb-bbri/spotutils.base"
TAG=${TAG:-"latest"}

# ABSOLUTE PATH OF THIS SCRIPT'S DIRECTORY
runpath="$( cd "$(dirname "$0")" ; pwd -P )"
(cd ${runpath} &&
    docker build --file ${runpath}/Dockerfile --pull --tag $IMAGE_NAME:$TAG ../.. &&
    docker push $IMAGE_NAME:$TAG)